# fly.toml app configuration file generated for digitalblockchain-sparkling-paper-1501 on 2024-08-20T11:37:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'digitalblockchain'
primary_region = 'dfw'
kill_signal = 'SIGTERM'

[build]

[deploy]
 # release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'digitalblockchain.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
