# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs: 
  test:
    machine:
      image: ubuntu-2204:edge
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build test application
          command: docker build -f Dockerfile.test .

  build:
    machine:
      image: ubuntu-2204:edge
      docker_layer_caching: true
    steps:
      - checkout

      # Replace this with steps to build a package, or executable
      - run:
          name: Build application
          command: docker build -t taguniversalsoftware/digitalblockchain:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Image to Docker Hub
          command: |
            docker push taguniversalsoftware/digitalblockchain:latest
   #   - store_artifacts:
   #       path: example.txt

  

  deploy:
    machine:
      image: ubuntu-2204:edge
    steps:
      - run:
          name: Install Fly CLI
          command: |
            curl -L https://fly.io/install.sh | sh
            export FLYCTL_INSTALL="/root/.fly"
            export PATH="$FLYCTL_INSTALL/bin:$PATH"
      - run:
          name: Login to Fly.io
          command: fly auth token ${FLY_API_TOKEN} # Assumes FLY_API_TOKEN is set in CircleCI environment variables
      - run:
          name: Deploy to Fly.io
          command: fly deploy -a digitalblockchain -i taguniversalsoftware/digitalblockchain:latest

workflows:
  my-workflow:
    jobs:
      - test
      - build:
          requires:
            - test

      - deploy:
          requires:
            - build
         
