# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs: 
  build:
    machine:
      image: ubuntu-2204:edge
      docker_layer_caching: true
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: docker build -t taguniversalsoftware/digitalblockchain:latest .
   #   - store_artifacts:
   #       path: example.txt

  test:
    docker:
      image: taguniversalsoftware/digitalblockchain:latest
      docker_layer_caching: true
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: mix test
  
  deploy:
    docker:
      image: taguniversalsoftware/digitalblockchain:latest
      docker_layer_caching: true
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: mix release

workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
